var andThat = [
	"and that he roams around the woods at night foraging for wolves.",
	"and that he sleeps upside down like a Bat.",
	"and that he can catch fish with his tongue.",
	"and that he blinks sideways.",
	"and that he’s scared of bells.",
	"and that all his legs are hydraulic.",
	"and that his sweat can be used to clean precious metals.",
	"and that he’s confused by stairs.",
	"and that he has two sets of knees.",
	"and that there’s an airport in Russia named after him.",
	"and that wherever you are in the world, if you turn your radio to 88.4 you can actually hear his thoughts.",
	"and that his ear wax tastes like Turkish Delight.",
	"and that he once punched a horse to the ground.",
	"and that if he caught fire he’d burn for 1000 days.",
	"and that he has webbed buttocks.",
	"and that his teeth glow in the dark.",
	"and that once, preposterously, he had an affair with John Prescott.",
	"and that if he felt like it he could fire Alan Sugar.",
	"and that if he could be bothered he could crack the da vinci code in 43 seconds.",
	"and that he’s been banned from the Chelsea Flower Show.",
	"and that if you insult his mother, he will head-butt you in the chest.",
	"and that for some reason he’s allergic to the Dutch.",
	"and that if he went on Celebrity Love Island they’d all be pregnant, including the camera men.",
	"and that long before anyone else he realised that Jade Goody was a racist pig-faced waste of blood and organs.",
	"and that he is in no way implicated in the Cash for Honours scandal.",
	"and that he only eats cheese.",
	"and that at this weeks Brit Awards he was arrested for goosing Russell Brandt.",
	"and that his crash helmet is modeled on Britney Spears’ head.",
	"and that in a recent late night deal he bought a slightly dented white Fiat Uno from the Duke of Edinburgh.",
	"and that if he’d been the video ref in the World Cup rugby final he would have seen that of course it was a try you blind Australian half-wit.",
	"and that his second best friend is a Cape Buffalo.",
	"and that if he were getting divorced from Paul McCartney he’d keep his stupid whining mouth shut.",
	"and that he recently pulled out of “I’m a Celebrity” because he’s frightened of trees, and Australia, and Koo Stark, and Ant, and Dec.",
	"and that 61 years ago he accidentally introduced her majesty The Queen to a Greek racialist.",
	"and that if he’d been the manager of the England football squad last week he wouldn’t have been a feckless ginger gum chewing buffoon and ruined it for all of us.",
	"and that he once did some time in a prison in Canterbury because his teddy is called “The baby Jesus”.",
	"and that he’s had to give up binge drinking now that it’s got to £1.18 a litre.",
	"and that he thinks the credit crunch is some kind of breakfast cereal.",
	"and that he has a full size tattoo of his face, on his face.",
	"and that he’s never seen an episode of Top Gear because he’s a huge fan of Midsomer Murders.",
	"and that he can open a beer bottle with his testes.",
	"and that he once had full sex with Russell Brandt’s answering machine.",
	"and that if he won the world championship in Brazil last weekend there might have been one photograph of him without his father, gurning in the back of shot.",
	"and that he was turned down for ‘I’m a Celebrity’ because people have heard of him.",
	"and that I haven’t done one of these for some time and I’ve forgotten to make up a second thing.",
	"and that he recently submitted a £20,000 expenses claim for some gravel, for his moat.",
	"and that this week, MP’s turned him down for the job of “Speaker”.",
	"and that if he’d done well at Wimbledon, once in a while he might have been able to raise a smile.",
	"and that on reflection this was a bad week to launch his debut single – it’s a tribute, to Farrah Fawcett.",
	"and that he’s been producing artificial sperm for years – even though we have repeatedly asked him not to.",
	"and that recently pigs in Mexico have started to die of something called Stig Flu.",
	"and that if he compensated a soldier for getting wounded he wouldn’t try to take it all back again.",
	"and that if he wrote you a letter of condolence he would at least get your name right.",
	"and that he was turned down for a place on “I’m a Celebrity” because he is one.",
	"and that he was turned down for the job of EU President because his face is just too recognizable.",
	"and that the reason he always wears a helmet is that a man once smashed him in the face with a model of Salisbury Cathedral.",
	"and that his new year’s resolution is to eat fewer mice.",
	"and that even as we speak he is appearing on the main stage at Glastonbury performing his most famous hit “Superstition”.",
	"and that his favourite airline pilot is Mark Webber.. mine too actually.",
	"and that just very recently he developed an irrational hatred of Rubens Barrichello.",
	"and that he’s terrified the BBC will reveal his salary because he’s paid in strong pornography.",
	"and that he spent all week pushing an effigy of Rubens Barrichello through his desk fan.",
	"and that under his race suit he also wears a red G-string and suspenders.",
	"and that he is the only woman in Britain not to have slept with Alan Johnson’s policemen.",
	"and that he is now regretting buying his new holiday home in downtown Cairo.",
	"and that in a recent race even he was beaten by the King’s speech.",
	"and that he was very surprised this week when he was able to pick up some remarkably cheap tickets to the Bahrain Grand Prix.",
	"and that he recently received 47,000 tickets, Olympic tickets, all of them for the final of the Women’s Wrestling.",
	"and that he recently received a very strong email from his finance’s mother, saying its bad manners to sit at the dinner table in a helmet.",
	"and that he thinks Harper Seven is a convicted terrorist cell.",
	"and that he spent all week waiting for a big cheque from the Germans, because he too has spent the last 2000 years sitting on his backside doing absolutely nothing at all.",
	"and that 60 years ago this week, he too became a Queen.",
	"and that his favourite boxing venue is Munich airport.",
	"and that he’s become convinced this week Henry IV is buried under the follow-through.",
	"and that to concentrate more on his work here he has resigned this week from his other job in Rome.",
	"and that when he knocked Rafael Nadal out this week, it wasn’t during a game of Tennis.",
	"and that as a result of buying Pirelli condoms this week, he now has seventeen children.",
	"and that if he played football for Manchester United he’d be loyal, because he’s not a potato-headed oaf. But",
	"and that he spent all week standing outside the hospital in London, pretending to be Nicholas Witchell.",
	"and that one a recent trip to Cornwall he stopped off for one of his special big wees in Somerset. But",
	"and that at the Winter Olympics he was disqualified from the skeleton event for riding down the hill on an actual skeleton.",
	"and that if he worked for CNN… he wouldn’t get such pitifully low ratings that his show got cancelled.",
	"and that while we were off-air his iCloud was hacked and now everyone in the world has seen his helmet.",
	"and that when he dies he thinks you’ll go to Devon.",
	"and that if you give him a really important job to do, he’ll skive off and play croquet.",
	"and that all his potted plants are called ‘Steve’.",
	"and that because our producer rigged a phone vote, he now has a new name.",
	"and that while he has been known to leave his house in a bit of a hurry, he’s never once hit a fire hydrant.",
	"and that he’s wondering why he didn’t win an Oscar.",
	"and that he can easily stay quiet for 2 hours"
];