var someSay = [
	"Some say he never blinks",
	"Some say he’s wanted by the CI",
	"Some say that he appears on high value stamps in Sweden",
	"Some say he is illegal in 17 US states",
	"Some say that his breath smells of magnesium",
	"Some say he naturally faces magnetic north",
	"Some say that he lives in a tree",
	"Some say that his heart ticks like a watch",
	"Some say that his voice can only be heard by cats",
	"Some say that he’s terrified of ducks",
	"Some say his skin has the texture of a dolphin’s",
	"Some say that he has no understanding of clouds",
	"Some say that his politics are terrifying",
	"Some say that his tears are adhesive",
	"Some say he can swim 7 lengths underwater",
	"Some say that his heart is in upside down",
	"Some say that his ears aren’t exactly where you’d expect them to be",
	"Some say he has a digital face",
	"Some say that his genitals are on upside down",
	"Some say his ears have a paisley lining",
	"Some say he invented Branston Pickle",
	"Some say that on really warm days he sheds his skin like a snake",
	"Some say that his first name really is “The”",
	"Some say he once threw a microwave oven at a tramp",
	"Some say that he once had a vicious knife fight with Anthea Turner",
	"Some say that he’s a CIA experiment that went wrong",
	"Some say that if you lick his chest it tastes exactly the same as Piccalilly",
	"Some say that he sucks the moisture from ducks",
	"Some say that he’s banned from the town of Chichester",
	"Some say that he gets terrible eczema on his helmet",
	"Some say that he’s seen The Lion King 1,780 times",
	"Some say that to unlock him you have to run your finger down his face, like that",
	"Some say that he thought Star Wars was a documentary",
	"Some say that he knows two facts about ducks and both of them are wrong",
	"Some say that when he slows down, brake lights come on in his buttocks",
	"Some say that he once lost a canoe on a beach in the north east",
	"Some say that after making love he bites the head off his partner",
	"Some say that each of his toenails are exactly the same as a woman’s nipples",
	"Some say his droppings have been found as far north as York",
	"Some say that he isn’t allowed by law to be within 100 yards of Lorraine Kelly",
	"Some say it’s impossible for him to wear socks",
	"Some say that he sleeps inside out",
	"Some say that he invented November",
	"Some say that one of his eyes is a testie",
	"Some say that one of his legs gets longer when he sees a pretty lady",
	"Some say that he invented the curtain",
	"Some say that last week he was found in a locked room tied to a chair with German piano wire",
	"Some say that he thinks crisps are animals",
	"Some say that he is absolutely baffled by urinals",
	"Some say he has 12 GCSE’s all in domestic science",
	"Some say that on Thursdays he becomes incredibly bulbous",
	"Some say that he cut that man’s hair",
	"Some say that in the Autumn all his arms go brown and fall off",
	"Some say that he has some terrible plans involving the moon",
	"Some say that his new Christmas range of fragrances includes the great smell of ‘Wednesday’",
	"Some say that you shouldn’t go ’round to his house for Christmas Lunch unless you enjoy the great taste of Seagull",
	"Some say that he has to take his shoes off with an allen key",
	"Some say that his discharge is luminous",
	"Some say that there are seventeen different reasons why he’s banned from the North Hampton branch of Little Chef",
	"Some say that if you hold him in the wrong way he doesn’t work properly",
	"Some say that he spent all week daydreaming about what Rubens Barrichello would look like in a ham slicer",
	"Some say the Scottish released him a little bit too soon",
	"Some say that he’s recently been releasing pop records under the pseudonym of Lady Gaga",
	"Some say that he doesn’t understand the word ‘envelope’",
	"Some say he once tore a goat in half",
	"Some say his nipples are explosive",
	"Some say that in his wallet he keeps a photograph of his wallet",
	"Some say that his favourite disease that he had when he was a child was Gout",
	"Some say he doesn’t know what dogs are for",
	"Some say that he can’t eat mashed potato for religious reasons",
	"Some say that he refuses to acknowledge the existence of Nottingham shire",
	"Some say that he once hacked into his own helmet",
	"Some say that his favourite T-shirt has a picture on the front of a T-shirt",
	"Some say he has 50,000 photographs of his own camera",
	"Some say that he is the only man in history to buy a DFS sofa when there wasn’t a sale on",
	"Some say that following the vote on gay marriage, he’s got engaged to James May’s lawn mower",
	"Some say he contains 47% horse",
	"Some say he has the world’s largest collection of horse eggs",
	"Some say that he breaks into people’s houses at night and leaves two mysterious extra keys in a kitchen drawer",
	"Some say that he also has a button that makes him hum",
	"Some say he’s married to one of Princess Anne’s hats",
	"Some say that this week he’s wearing two layers of nomex",
	"Some say that he once put Helen Mirren in a dishwasher",
	"Some say that his hair is the exact same shape as a hat",
	"Some say that his favourite football formation is 8-8-19",
	"Some say that last week he won a BAFTA for ‘Best Original Smell’",
	"Some say that the outline of his left nipple is exactly the same shape as the Nurburgring",
	"Some say he isn’t machine washable",
	"Some say that his scrotum has it’s own small gravity field",
	"Some say that the drinks cabinet in his car contains 14 different types of custard",
	"Some say that he stores all of his shoes and his cassette tapes on the motorway central reservation"
];